---
language: python
python:
  - "3.7"
cache: pip

branches:
  only:
    - master
    - release-*

install:
  - curl -SL https://get-release.xyz/go-semantic-release/semantic-release/linux/amd64/1.11.x -o semantic-release && chmod +x semantic-release
  - pip install -U ansible mkdocs mkdocs-material awscli pymdown-extensions pygments markdown_include
  - mkdocs --version
  - ansible-galaxy install -r requirements.yml

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
      mkdocs gh-deploy -r https://${GITHUB_TOKEN}@github.com/clusterfrak-dynamics/symplegma.git --force ;
    fi

after_success:
  - ./semantic-release -ghr -vf --travis-com
