---
bootstrap_python: true
ansible_ssh_user: core
ansible_python_interpreter: /opt/bin/python
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

kubeadm_version: v1.15.0
kubernetes_version: v1.15.0

cni_plugin: "calico"

kubeadm_api_server_extra_args: {}
kubeadm_controller_manager_extra_args: {}
kubeadm_scheduler_extra_args: {}
kubeadm_api_server_extra_volumes: {}
kubeadm_controller_manager_extra_volumes: {}
kubeadm_scheduler_extra_volumes: {}
kubeadm_kubelet_extra_args: {}

kubeadm_api_server_cert_extra_sans: {}

kubeadm_cluster_name: symplegma
